name: Compilacion de Aplicacion

on:
  push:
    [cite_start]branches: [ "main" ] # Se activa al subir código [cite: 12]

jobs:
  build:
    [cite_start]runs-on: windows-latest # Entorno para el .exe [cite: 16]

    steps:
    - uses: actions/checkout@v3 # Descarga tu código

    - name: Configurar Python
      [cite_start]uses: actions/setup-python@v4 # Prepara Python [cite: 14]
      with:
        python-version: '3.10'

    - name: Instalar librerias
      run: |
        pip install PySide6 pyinstaller # Instala dependencias [cite: 15]

    - name: Generar Ejecutables
      run: |
        pyinstaller --onefile --windowed main.py # Crea el .exe [cite: 4, 16]

    - name: Crear Artifact
      [cite_start]uses: actions/upload-artifact@v3 # Genera el archivo descargable 
      with:
        name: Programa-Ejecutable
        path: dist/main.exe