name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    [cite_start]runs-on: windows-latest  # Para generar el .exe [cite: 16]

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        [cite_start]python-version: '3.10' [cite: 14]

    - name: Instalar dependencias
      run: |
        pip install PySide6 pyinstaller [cite: 15]

    - name: Generar Ejecutable .exe
      run: |
        pyinstaller --onefile --windowed main.py [cite: 16]

    - name: Subir Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Aplicacion-Windows
        [cite_start]path: dist/main.exe [cite: 17]